// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_configs.djinni

package ch.admin.geo.openswissmaps.shared.layers.config

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

abstract class SwisstopoTiledLayerConfigFactory {

    companion object {
        @JvmStatic
        external fun createRasterTileLayerConfig(layerType: SwisstopoLayerType): io.openmobilemaps.mapscore.shared.map.layers.tiled.Tiled2dMapLayerConfig

        @JvmStatic
        external fun createRasterTileLayerConfigWithZoomInfo(layerType: SwisstopoLayerType, zoomInfo: io.openmobilemaps.mapscore.shared.map.layers.tiled.Tiled2dMapZoomInfo?): io.openmobilemaps.mapscore.shared.map.layers.tiled.Tiled2dMapLayerConfig

        @JvmStatic
        external fun createRasterTileLayerConfigWithBaseUrl(layerType: SwisstopoLayerType, zoomInfo: io.openmobilemaps.mapscore.shared.map.layers.tiled.Tiled2dMapZoomInfo?, baseUrl: String?): io.openmobilemaps.mapscore.shared.map.layers.tiled.Tiled2dMapLayerConfig

        @JvmStatic
        external fun createRasterTiledLayerConfigFromMetadata(configuration: io.openmobilemaps.mapscore.shared.map.layers.tiled.raster.wmts.WmtsLayerDescription, maxZoom: Int, zoomInfo: io.openmobilemaps.mapscore.shared.map.layers.tiled.Tiled2dMapZoomInfo): io.openmobilemaps.mapscore.shared.map.layers.tiled.Tiled2dMapLayerConfig
    }

    private class CppProxy : SwisstopoTiledLayerConfigFactory {
        private val nativeRef: Long
        private val destroyed: AtomicBoolean = AtomicBoolean(false)

        private constructor(nativeRef: Long) {
            if (nativeRef == 0L) error("nativeRef is zero")
            this.nativeRef = nativeRef
            NativeObjectManager.register(this, nativeRef)
        }

        companion object {
            @JvmStatic
            external fun nativeDestroy(nativeRef: Long)
        }
    }
}
