// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_swiss_maps.djinni

#pragma once

#include <string>

class OpenSwissMapsSharedModule {
public:
    virtual ~OpenSwissMapsSharedModule() {}

    static std::string version();
};
