// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from open_swiss_maps.djinni

#pragma once

#include <string>

class OpenSwissMapsSharedModule {
public:
    virtual ~OpenSwissMapsSharedModule() = default;

    static std::string version();
};
