// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_configs.djinni

#pragma once

#include "Tiled2dMapLayerConfig.h"
#include <memory>

enum class SwisstopoLayerType;

class SwisstopoTiledLayerConfigFactory {
public:
    virtual ~SwisstopoTiledLayerConfigFactory() {}

    static std::shared_ptr<::Tiled2dMapLayerConfig> createRasterTileLayerConfig(SwisstopoLayerType layerType);
};
