// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layers.djinni

#pragma once

#include "SwisstopoLayerType.h"
#include "TextureLoaderInterface.h"
#include "Tiled2dMapRasterLayerInterface.h"
#include "Tiled2dMapZoomInfo.h"
#include "WmtsLayerConfiguration.h"
#include <cstdint>
#include <memory>
#include <string>

class SwisstopoLayerFactory {
public:
    virtual ~SwisstopoLayerFactory() {}

    static std::shared_ptr<::Tiled2dMapRasterLayerInterface> createSwisstopoTiledRasterLayer(::SwisstopoLayerType layerType, const std::shared_ptr<::TextureLoaderInterface> & textureLoader);

    static std::shared_ptr<::Tiled2dMapRasterLayerInterface> createSwisstopoTiledRasterLayerFromMetadata(const std::string & identifier, const ::WmtsLayerConfiguration & configuration, int32_t maxZoom, const ::Tiled2dMapZoomInfo & zoomInfo, const std::shared_ptr<::TextureLoaderInterface> & textureLoader);
};
