// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layers.djinni

#pragma once

#include "SwisstopoLayerType.h"
#include "TextureLoaderInterface.h"
#include "Tiled2dMapRasterLayerInterface.h"
#include <memory>

class SwisstopoLayerFactory {
public:
    virtual ~SwisstopoLayerFactory() {}

    static std::shared_ptr<::Tiled2dMapRasterLayerInterface> createSwisstopoTiledRasterLayer(::SwisstopoLayerType layerType, const std::shared_ptr<::TextureLoaderInterface> & textureLoader);
};
