// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_configs.djinni

#pragma once

#include <functional>

enum class SwisstopoLayerType : int {
    PIXELKARTE_FARBE,
    PIXELKARTE_FARK_PK1000,
    PIXELKARTE_GRAUSTUFEN,
    PIXELKARTE_FARBE_WINTER,
    SWISSIMAGE,
    LUFTFAHRTKARTEN_ICAO,
    SEGELFLUGKARTE,
    MIL_AIRSPACE_CHART,
    SPERR_GEFAHRENZONENKARTE,
    SWISSMILPILOTSCHART,
    HIKS_DUFOR,
    HIKS_SIEGFRIED,
    SWISSTLM3D_EISENBAHNNETZ,
    SWISSTLM3D_STRASSEN,
    SWISSTLM3D_UEBRIGVERKEHR,
    SWISSTLM3D_WANDERWEGE,
    SCHWEIZMOBIL_WANDERLAND,
    SCHWEIZMOBIL_VELOLAND,
    SCHWEIZMOBIL_MOUNTAINBIKELAND,
    HANGNEIGUNG_30,
    HANGNEIGUNGSKLASSEN_30,
    WILDSCHUTZ_GEBIETE,
    WILDRUHEZONEN,
    SCHNEESCHUH_ROUTEN,
    SKI_TOUR_ROUTEN,
    DROHNEN,
    SCHUTZGEBIETE_LUFTFAHRT,
};

namespace std {

template <>
struct hash<::SwisstopoLayerType> {
    size_t operator()(::SwisstopoLayerType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
