// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_configs.djinni

#pragma once

#include "Tiled2dMapLayerConfig.h"
#include "Tiled2dMapZoomInfo.h"
#include "WmtsLayerDescription.h"
#include <cstdint>
#include <memory>
#include <optional>
#include <string>

enum class SwisstopoLayerType;

class SwisstopoTiledLayerConfigFactory {
public:
    virtual ~SwisstopoTiledLayerConfigFactory() = default;

    static /*not-null*/ std::shared_ptr<::Tiled2dMapLayerConfig> createRasterTileLayerConfig(SwisstopoLayerType layerType);

    static /*not-null*/ std::shared_ptr<::Tiled2dMapLayerConfig> createRasterTileLayerConfigWithZoomInfo(SwisstopoLayerType layerType, const std::optional<::Tiled2dMapZoomInfo> & zoomInfo);

    static /*not-null*/ std::shared_ptr<::Tiled2dMapLayerConfig> createRasterTileLayerConfigWithBaseUrl(SwisstopoLayerType layerType, const std::optional<::Tiled2dMapZoomInfo> & zoomInfo, const std::optional<std::string> & baseUrl);

    static /*not-null*/ std::shared_ptr<::Tiled2dMapLayerConfig> createRasterTiledLayerConfigFromMetadata(const ::WmtsLayerDescription & configuration, int32_t maxZoom, const ::Tiled2dMapZoomInfo & zoomInfo);
};
