// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_configs.djinni

#pragma once

#include "SwisstopoTiledLayerConfigFactory.h"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeSwisstopoTiledLayerConfigFactory final : ::djinni::JniInterface<::SwisstopoTiledLayerConfigFactory, NativeSwisstopoTiledLayerConfigFactory> {
public:
    using CppType = std::shared_ptr<::SwisstopoTiledLayerConfigFactory>;
    using CppOptType = std::shared_ptr<::SwisstopoTiledLayerConfigFactory>;
    using JniType = jobject;

    using Boxed = NativeSwisstopoTiledLayerConfigFactory;

    ~NativeSwisstopoTiledLayerConfigFactory();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeSwisstopoTiledLayerConfigFactory>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeSwisstopoTiledLayerConfigFactory>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeSwisstopoTiledLayerConfigFactory();
    friend ::djinni::JniClass<NativeSwisstopoTiledLayerConfigFactory>;
    friend ::djinni::JniInterface<::SwisstopoTiledLayerConfigFactory, NativeSwisstopoTiledLayerConfigFactory>;

};

} // namespace djinni_generated
