// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_configs.djinni

#pragma once

#include "SwisstopoLayerType.h"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeSwisstopoLayerType final : ::djinni::JniEnum {
public:
    using CppType = ::SwisstopoLayerType;
    using JniType = jobject;

    using Boxed = NativeSwisstopoLayerType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeSwisstopoLayerType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeSwisstopoLayerType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeSwisstopoLayerType() : JniEnum("ch/admin/geo/openswissmaps/shared/layers/config/SwisstopoLayerType") {}
    friend ::djinni::JniClass<NativeSwisstopoLayerType>;
};

} // namespace djinni_generated
