// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from open_swiss_maps.djinni

package io.openmobilemaps.openswissmaps.kmp

expect class KMOpenSwissMapsSharedModule constructor(nativeHandle: Any) {

    companion object
    {

        fun version(): String
    }
}
