// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layers.djinni

package io.openmobilemaps.openswissmaps.kmp

expect class KMSwisstopoLayerFactory constructor(nativeHandle: Any) {

    companion object
    {

        fun createSwisstopoTiledRasterLayer(layerType: io.openmobilemaps.openswissmaps.kmp.KMSwisstopoLayerType, tileLoaders: List<io.openmobilemaps.mapscore.kmp.KMLoaderInterface>): io.openmobilemaps.mapscore.kmp.KMTiled2dMapRasterLayerInterface

        fun createSwisstopoTiledRasterLayerFromMetadata(description: io.openmobilemaps.mapscore.kmp.KMWmtsLayerDescription, maxZoom: Int, zoomInfo: io.openmobilemaps.mapscore.kmp.KMTiled2dMapZoomInfo, tileLoaders: List<io.openmobilemaps.mapscore.kmp.KMLoaderInterface>): io.openmobilemaps.mapscore.kmp.KMTiled2dMapRasterLayerInterface
    }
}
