// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_configs.djinni

package io.openmobilemaps.openswissmaps.kmp

expect class KMSwisstopoTiledLayerConfigFactory constructor(nativeHandle: Any) {

    companion object
    {

        fun createRasterTileLayerConfig(layerType: KMSwisstopoLayerType): io.openmobilemaps.mapscore.kmp.KMTiled2dMapLayerConfig

        fun createRasterTileLayerConfigWithZoomInfo(layerType: KMSwisstopoLayerType, zoomInfo: io.openmobilemaps.mapscore.kmp.KMTiled2dMapZoomInfo?): io.openmobilemaps.mapscore.kmp.KMTiled2dMapLayerConfig

        fun createRasterTileLayerConfigWithBaseUrl(layerType: KMSwisstopoLayerType, zoomInfo: io.openmobilemaps.mapscore.kmp.KMTiled2dMapZoomInfo?, baseUrl: String?): io.openmobilemaps.mapscore.kmp.KMTiled2dMapLayerConfig

        fun createRasterTiledLayerConfigFromMetadata(configuration: io.openmobilemaps.mapscore.kmp.KMWmtsLayerDescription, maxZoom: Int, zoomInfo: io.openmobilemaps.mapscore.kmp.KMTiled2dMapZoomInfo): io.openmobilemaps.mapscore.kmp.KMTiled2dMapLayerConfig

        fun createZoomLevelInfos(): List<io.openmobilemaps.mapscore.kmp.KMTiled2dMapZoomLevelInfo>
    }
}
