// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layers.djinni

package ch.admin.geo.openswissmaps.shared.layers

import java.util.concurrent.atomic.AtomicBoolean

abstract class SwisstopoLayerFactory {

    companion object {
        @JvmStatic
        fun createSwisstopoTiledRasterLayer(layerType: ch.admin.geo.openswissmaps.shared.layers.config.SwisstopoLayerType, loader: io.openmobilemaps.mapscore.shared.map.loader.LoaderInterface): io.openmobilemaps.mapscore.shared.map.layers.tiled.raster.Tiled2dMapRasterLayerInterface {
            return CppProxy.createSwisstopoTiledRasterLayer(layerType, loader)
        }

        @JvmStatic
        fun createSwisstopoTiledRasterLayerFromMetadata(description: io.openmobilemaps.mapscore.shared.map.layers.tiled.raster.wmts.WmtsLayerDescription, maxZoom: Int, zoomInfo: io.openmobilemaps.mapscore.shared.map.layers.tiled.Tiled2dMapZoomInfo, loader: io.openmobilemaps.mapscore.shared.map.loader.LoaderInterface): io.openmobilemaps.mapscore.shared.map.layers.tiled.raster.Tiled2dMapRasterLayerInterface {
            return CppProxy.createSwisstopoTiledRasterLayerFromMetadata(description, maxZoom, zoomInfo, loader)
        }
    }

    private class CppProxy : SwisstopoLayerFactory {
        private val nativeRef: Long
        private val destroyed: AtomicBoolean = AtomicBoolean(false)

        private constructor(nativeRef: Long) {
            if (nativeRef == 0L) error("nativeRef is zero")
            this.nativeRef = nativeRef
        }

        private external fun nativeDestroy(nativeRef: Long)
        fun _djinni_private_destroy() {
            val destroyed = this.destroyed.getAndSet(true)
            if (!destroyed) nativeDestroy(this.nativeRef)
        }
        protected fun finalize() {
            _djinni_private_destroy()
        }

        companion object {
            @JvmStatic
            external fun createSwisstopoTiledRasterLayer(layerType: ch.admin.geo.openswissmaps.shared.layers.config.SwisstopoLayerType, loader: io.openmobilemaps.mapscore.shared.map.loader.LoaderInterface): io.openmobilemaps.mapscore.shared.map.layers.tiled.raster.Tiled2dMapRasterLayerInterface

            @JvmStatic
            external fun createSwisstopoTiledRasterLayerFromMetadata(description: io.openmobilemaps.mapscore.shared.map.layers.tiled.raster.wmts.WmtsLayerDescription, maxZoom: Int, zoomInfo: io.openmobilemaps.mapscore.shared.map.layers.tiled.Tiled2dMapZoomInfo, loader: io.openmobilemaps.mapscore.shared.map.loader.LoaderInterface): io.openmobilemaps.mapscore.shared.map.layers.tiled.raster.Tiled2dMapRasterLayerInterface
        }
    }
}
