// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layers.djinni

package ch.admin.geo.openswissmaps.shared.layers

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

abstract class SwisstopoLayerFactory {

    companion object {
        @JvmStatic
        external fun createSwisstopoTiledRasterLayer(layerType: ch.admin.geo.openswissmaps.shared.layers.config.SwisstopoLayerType, tileLoaders: ArrayList<io.openmobilemaps.mapscore.shared.map.loader.LoaderInterface>): io.openmobilemaps.mapscore.shared.map.layers.tiled.raster.Tiled2dMapRasterLayerInterface

        @JvmStatic
        external fun createSwisstopoTiledRasterLayerFromMetadata(description: io.openmobilemaps.mapscore.shared.map.layers.tiled.raster.wmts.WmtsLayerDescription, maxZoom: Int, zoomInfo: io.openmobilemaps.mapscore.shared.map.layers.tiled.Tiled2dMapZoomInfo, tileLoaders: ArrayList<io.openmobilemaps.mapscore.shared.map.loader.LoaderInterface>): io.openmobilemaps.mapscore.shared.map.layers.tiled.raster.Tiled2dMapRasterLayerInterface
    }

    private class CppProxy : SwisstopoLayerFactory {
        private val nativeRef: Long
        private val destroyed: AtomicBoolean = AtomicBoolean(false)

        private constructor(nativeRef: Long) {
            if (nativeRef == 0L) error("nativeRef is zero")
            this.nativeRef = nativeRef
            NativeObjectManager.register(this, nativeRef)
        }

        external fun nativeDestroy(nativeRef: Long)
    }
}
