// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from open_swiss_maps.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.openswissmaps.kmp

import swiftPMImport.io.openmobilemaps.openswissmaps.kmp.STSDKOpenSwissMapsSharedModule

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMOpenSwissMapsSharedModule", exact = true)
actual class KMOpenSwissMapsSharedModule actual public constructor(
    nativeHandle: Any,
) {
    internal val nativeHandle: Any = nativeHandle
    private val native = nativeHandle as STSDKOpenSwissMapsSharedModule

    actual companion object
    {

        actual fun version(): String {
            val result = STSDKOpenSwissMapsSharedModule.version()
            return result
        }
    }
}

public fun KMOpenSwissMapsSharedModule.asPlatform(): STSDKOpenSwissMapsSharedModule = nativeHandle as STSDKOpenSwissMapsSharedModule
public fun STSDKOpenSwissMapsSharedModule.asKmp(): KMOpenSwissMapsSharedModule = KMOpenSwissMapsSharedModule(this)
