// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layers.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.openswissmaps.kmp

import io.openmobilemaps.mapscore.kmp.asKmp
import io.openmobilemaps.mapscore.kmp.asPlatform
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCLoaderInterfaceProtocol
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCTiled2dMapRasterLayerInterface
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCTiled2dMapZoomInfo
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCWmtsLayerDescription
import swiftPMImport.io.openmobilemaps.openswissmaps.kmp.STSDKSwisstopoLayerFactory
import swiftPMImport.io.openmobilemaps.openswissmaps.kmp.STSDKSwisstopoLayerType

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMSwisstopoLayerFactory", exact = true)
actual class KMSwisstopoLayerFactory actual public constructor(
    nativeHandle: Any,
) {
    internal val nativeHandle: Any = nativeHandle
    private val native = nativeHandle as STSDKSwisstopoLayerFactory

    actual companion object
    {

        actual fun createSwisstopoTiledRasterLayer(layerType: io.openmobilemaps.openswissmaps.kmp.KMSwisstopoLayerType, tileLoaders: List<io.openmobilemaps.mapscore.kmp.KMLoaderInterface>): io.openmobilemaps.mapscore.kmp.KMTiled2dMapRasterLayerInterface {
            val result = STSDKSwisstopoLayerFactory.createSwisstopoTiledRasterLayer(layerType.asPlatform(), ArrayList(tileLoaders.map { it.asPlatform() }))
            return (result as MCTiled2dMapRasterLayerInterface).asKmp()
        }

        actual fun createSwisstopoTiledRasterLayerFromMetadata(description: io.openmobilemaps.mapscore.kmp.KMWmtsLayerDescription, maxZoom: Int, zoomInfo: io.openmobilemaps.mapscore.kmp.KMTiled2dMapZoomInfo, tileLoaders: List<io.openmobilemaps.mapscore.kmp.KMLoaderInterface>): io.openmobilemaps.mapscore.kmp.KMTiled2dMapRasterLayerInterface {
            val result = STSDKSwisstopoLayerFactory.createSwisstopoTiledRasterLayerFromMetadata(description.asPlatform(), maxZoom, zoomInfo.asPlatform(), ArrayList(tileLoaders.map { it.asPlatform() }))
            return (result as MCTiled2dMapRasterLayerInterface).asKmp()
        }
    }
}

public fun KMSwisstopoLayerFactory.asPlatform(): STSDKSwisstopoLayerFactory = nativeHandle as STSDKSwisstopoLayerFactory
public fun STSDKSwisstopoLayerFactory.asKmp(): KMSwisstopoLayerFactory = KMSwisstopoLayerFactory(this)
