// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_configs.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.openswissmaps.kmp

import swiftPMImport.io.openmobilemaps.openswissmaps.kmp.STSDKSwisstopoLayerType

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMSwisstopoLayerType", exact = true)
actual enum class KMSwisstopoLayerType(internal val platformValue: Long) {
    PIXELKARTE_FARBE(0L),
    PIXELKARTE_FARK_PK1000(1L),
    PIXELKARTE_GRAUSTUFEN(2L),
    PIXELKARTE_FARBE_WINTER(3L),
    SWISSIMAGE(4L),
    SWISSIMAGE_1946(5L),
    LUFTFAHRTKARTEN_ICAO(6L),
    SEGELFLUGKARTE(7L),
    MIL_AIRSPACE_CHART(8L),
    SPERR_GEFAHRENZONENKARTE(9L),
    SWISSMILPILOTSCHART(10L),
    HIKS_DUFOR(11L),
    HIKS_SIEGFRIED(12L),
    SWISSTLM3D_EISENBAHNNETZ(13L),
    SWISSTLM3D_STRASSEN(14L),
    SWISSTLM3D_UEBRIGVERKEHR(15L),
    SWISSTLM3D_WANDERWEGE(16L),
    SCHWEIZMOBIL_WANDERLAND(17L),
    SCHWEIZMOBIL_VELOLAND(18L),
    SCHWEIZMOBIL_MOUNTAINBIKELAND(19L),
    HANGNEIGUNG_30(20L),
    HANGNEIGUNGSKLASSEN_30(21L),
    WILDSCHUTZ_GEBIETE(22L),
    WILDRUHEZONEN(23L),
    SCHNEESCHUH_ROUTEN(24L),
    SKI_TOUR_ROUTEN(25L),
    DROHNEN(26L),
    SCHUTZGEBIETE_LUFTFAHRT(27L),
    EISZEIT(28L),
    ;

    companion object {
        public fun fromPlatform(value: STSDKSwisstopoLayerType): KMSwisstopoLayerType {
            val raw: Long = value
            return when (raw) {
                0L -> KMSwisstopoLayerType.PIXELKARTE_FARBE
                1L -> KMSwisstopoLayerType.PIXELKARTE_FARK_PK1000
                2L -> KMSwisstopoLayerType.PIXELKARTE_GRAUSTUFEN
                3L -> KMSwisstopoLayerType.PIXELKARTE_FARBE_WINTER
                4L -> KMSwisstopoLayerType.SWISSIMAGE
                5L -> KMSwisstopoLayerType.SWISSIMAGE_1946
                6L -> KMSwisstopoLayerType.LUFTFAHRTKARTEN_ICAO
                7L -> KMSwisstopoLayerType.SEGELFLUGKARTE
                8L -> KMSwisstopoLayerType.MIL_AIRSPACE_CHART
                9L -> KMSwisstopoLayerType.SPERR_GEFAHRENZONENKARTE
                10L -> KMSwisstopoLayerType.SWISSMILPILOTSCHART
                11L -> KMSwisstopoLayerType.HIKS_DUFOR
                12L -> KMSwisstopoLayerType.HIKS_SIEGFRIED
                13L -> KMSwisstopoLayerType.SWISSTLM3D_EISENBAHNNETZ
                14L -> KMSwisstopoLayerType.SWISSTLM3D_STRASSEN
                15L -> KMSwisstopoLayerType.SWISSTLM3D_UEBRIGVERKEHR
                16L -> KMSwisstopoLayerType.SWISSTLM3D_WANDERWEGE
                17L -> KMSwisstopoLayerType.SCHWEIZMOBIL_WANDERLAND
                18L -> KMSwisstopoLayerType.SCHWEIZMOBIL_VELOLAND
                19L -> KMSwisstopoLayerType.SCHWEIZMOBIL_MOUNTAINBIKELAND
                20L -> KMSwisstopoLayerType.HANGNEIGUNG_30
                21L -> KMSwisstopoLayerType.HANGNEIGUNGSKLASSEN_30
                22L -> KMSwisstopoLayerType.WILDSCHUTZ_GEBIETE
                23L -> KMSwisstopoLayerType.WILDRUHEZONEN
                24L -> KMSwisstopoLayerType.SCHNEESCHUH_ROUTEN
                25L -> KMSwisstopoLayerType.SKI_TOUR_ROUTEN
                26L -> KMSwisstopoLayerType.DROHNEN
                27L -> KMSwisstopoLayerType.SCHUTZGEBIETE_LUFTFAHRT
                28L -> KMSwisstopoLayerType.EISZEIT
                else -> throw IllegalArgumentException("Unknown KMSwisstopoLayerType value: " + raw)
            }
        }
    }
}

public fun KMSwisstopoLayerType.asPlatform(): STSDKSwisstopoLayerType = platformValue
