// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_configs.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.openswissmaps.kmp

import io.openmobilemaps.mapscore.kmp.asKmp
import io.openmobilemaps.mapscore.kmp.asPlatform
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCTiled2dMapLayerConfigProtocol
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCTiled2dMapZoomInfo
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCTiled2dMapZoomLevelInfo
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCWmtsLayerDescription
import swiftPMImport.io.openmobilemaps.openswissmaps.kmp.STSDKSwisstopoLayerType
import swiftPMImport.io.openmobilemaps.openswissmaps.kmp.STSDKSwisstopoTiledLayerConfigFactory

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMSwisstopoTiledLayerConfigFactory", exact = true)
actual class KMSwisstopoTiledLayerConfigFactory actual public constructor(
    nativeHandle: Any,
) {
    internal val nativeHandle: Any = nativeHandle
    private val native = nativeHandle as STSDKSwisstopoTiledLayerConfigFactory

    actual companion object
    {

        actual fun createRasterTileLayerConfig(layerType: KMSwisstopoLayerType): io.openmobilemaps.mapscore.kmp.KMTiled2dMapLayerConfig {
            val result = STSDKSwisstopoTiledLayerConfigFactory.createRasterTileLayerConfig(layerType.asPlatform())
            return (result as MCTiled2dMapLayerConfigProtocol).asKmp()
        }

        actual fun createRasterTileLayerConfigWithZoomInfo(layerType: KMSwisstopoLayerType, zoomInfo: io.openmobilemaps.mapscore.kmp.KMTiled2dMapZoomInfo?): io.openmobilemaps.mapscore.kmp.KMTiled2dMapLayerConfig {
            val result = STSDKSwisstopoTiledLayerConfigFactory.createRasterTileLayerConfigWithZoomInfo(layerType.asPlatform(), zoomInfo?.let { it.asPlatform() })
            return (result as MCTiled2dMapLayerConfigProtocol).asKmp()
        }

        actual fun createRasterTileLayerConfigWithBaseUrl(layerType: KMSwisstopoLayerType, zoomInfo: io.openmobilemaps.mapscore.kmp.KMTiled2dMapZoomInfo?, baseUrl: String?): io.openmobilemaps.mapscore.kmp.KMTiled2dMapLayerConfig {
            val result = STSDKSwisstopoTiledLayerConfigFactory.createRasterTileLayerConfigWithBaseUrl(layerType.asPlatform(), zoomInfo?.let { it.asPlatform() }, baseUrl?.let { it })
            return (result as MCTiled2dMapLayerConfigProtocol).asKmp()
        }

        actual fun createRasterTiledLayerConfigFromMetadata(configuration: io.openmobilemaps.mapscore.kmp.KMWmtsLayerDescription, maxZoom: Int, zoomInfo: io.openmobilemaps.mapscore.kmp.KMTiled2dMapZoomInfo): io.openmobilemaps.mapscore.kmp.KMTiled2dMapLayerConfig {
            val result = STSDKSwisstopoTiledLayerConfigFactory.createRasterTiledLayerConfigFromMetadata(configuration.asPlatform(), maxZoom, zoomInfo.asPlatform())
            return (result as MCTiled2dMapLayerConfigProtocol).asKmp()
        }

        actual fun createZoomLevelInfos(): List<io.openmobilemaps.mapscore.kmp.KMTiled2dMapZoomLevelInfo> {
            val result = STSDKSwisstopoTiledLayerConfigFactory.createZoomLevelInfos()
            return ArrayList(((result as? List<*>)?.map { (it as MCTiled2dMapZoomLevelInfo).asKmp() } ?: (0 until (result as platform.Foundation.NSArray).count.toInt()).map { idx -> ((result as platform.Foundation.NSArray).objectAtIndex(idx.toULong()) as MCTiled2dMapZoomLevelInfo).asKmp() }))
        }
    }
}

public fun KMSwisstopoTiledLayerConfigFactory.asPlatform(): STSDKSwisstopoTiledLayerConfigFactory = nativeHandle as STSDKSwisstopoTiledLayerConfigFactory
public fun STSDKSwisstopoTiledLayerConfigFactory.asKmp(): KMSwisstopoTiledLayerConfigFactory = KMSwisstopoTiledLayerConfigFactory(this)
