// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layers.djinni

#pragma once

#include "SwisstopoLayerFactory.h"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeSwisstopoLayerFactory final : ::djinni::JniInterface<::SwisstopoLayerFactory, NativeSwisstopoLayerFactory> {
public:
    using CppType = std::shared_ptr<::SwisstopoLayerFactory>;
    using CppOptType = std::shared_ptr<::SwisstopoLayerFactory>;
    using JniType = jobject;

    using Boxed = NativeSwisstopoLayerFactory;

    ~NativeSwisstopoLayerFactory();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeSwisstopoLayerFactory>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeSwisstopoLayerFactory>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeSwisstopoLayerFactory();
    friend ::djinni::JniClass<NativeSwisstopoLayerFactory>;
    friend ::djinni::JniInterface<::SwisstopoLayerFactory, NativeSwisstopoLayerFactory>;

};

}  // namespace djinni_generated
