// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from open_swiss_maps.djinni

#import <Foundation/Foundation.h>


@interface STSDKOpenSwissMapsSharedModule : NSObject

+ (nonnull NSString *)version;

@end
