// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layers.djinni

#import "MCLoaderInterface.h"
#import "MCTiled2dMapRasterLayerInterface.h"
#import "MCTiled2dMapZoomInfo.h"
#import "MCWmtsLayerDescription.h"
#import "STSDKSwisstopoLayerType.h"
#import <Foundation/Foundation.h>


@interface STSDKSwisstopoLayerFactory : NSObject

+ (nullable MCTiled2dMapRasterLayerInterface *)createSwisstopoTiledRasterLayer:(STSDKSwisstopoLayerType)layerType
                                                                   tileLoaders:(nonnull NSArray<id<MCLoaderInterface>> *)tileLoaders;

+ (nullable MCTiled2dMapRasterLayerInterface *)createSwisstopoTiledRasterLayerFromMetadata:(nonnull MCWmtsLayerDescription *)description
                                                                                   maxZoom:(int32_t)maxZoom
                                                                                  zoomInfo:(nonnull MCTiled2dMapZoomInfo *)zoomInfo
                                                                               tileLoaders:(nonnull NSArray<id<MCLoaderInterface>> *)tileLoaders;

@end
