// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from open_swiss_maps.djinni

#import "STSDKOpenSwissMapsSharedModule+Private.h"
#import "STSDKOpenSwissMapsSharedModule.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface STSDKOpenSwissMapsSharedModule ()

- (id)initWithCpp:(const std::shared_ptr<::OpenSwissMapsSharedModule>&)cppRef;

@end

@implementation STSDKOpenSwissMapsSharedModule {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::OpenSwissMapsSharedModule>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::OpenSwissMapsSharedModule>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nonnull NSString *)version {
    try {
        auto objcpp_result_ = ::OpenSwissMapsSharedModule::version();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto OpenSwissMapsSharedModule::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto OpenSwissMapsSharedModule::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<STSDKOpenSwissMapsSharedModule>(cpp);
}

}  // namespace djinni_generated

@end
