// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_configs.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, STSDKSwisstopoLayerType)
{
    STSDKSwisstopoLayerTypePIXELKARTE_FARBE = 0,
    STSDKSwisstopoLayerTypePIXELKARTE_FARK_PK1000 = 1,
    STSDKSwisstopoLayerTypePIXELKARTE_GRAUSTUFEN = 2,
    STSDKSwisstopoLayerTypePIXELKARTE_FARBE_WINTER = 3,
    STSDKSwisstopoLayerTypeSWISSIMAGE = 4,
    STSDKSwisstopoLayerTypeSWISSIMAGE_1946 = 5,
    STSDKSwisstopoLayerTypeLUFTFAHRTKARTEN_ICAO = 6,
    STSDKSwisstopoLayerTypeSEGELFLUGKARTE = 7,
    STSDKSwisstopoLayerTypeMIL_AIRSPACE_CHART = 8,
    STSDKSwisstopoLayerTypeSPERR_GEFAHRENZONENKARTE = 9,
    STSDKSwisstopoLayerTypeSWISSMILPILOTSCHART = 10,
    STSDKSwisstopoLayerTypeHIKS_DUFOR = 11,
    STSDKSwisstopoLayerTypeHIKS_SIEGFRIED = 12,
    STSDKSwisstopoLayerTypeSWISSTLM3D_EISENBAHNNETZ = 13,
    STSDKSwisstopoLayerTypeSWISSTLM3D_STRASSEN = 14,
    STSDKSwisstopoLayerTypeSWISSTLM3D_UEBRIGVERKEHR = 15,
    STSDKSwisstopoLayerTypeSWISSTLM3D_WANDERWEGE = 16,
    STSDKSwisstopoLayerTypeSCHWEIZMOBIL_WANDERLAND = 17,
    STSDKSwisstopoLayerTypeSCHWEIZMOBIL_VELOLAND = 18,
    STSDKSwisstopoLayerTypeSCHWEIZMOBIL_MOUNTAINBIKELAND = 19,
    STSDKSwisstopoLayerTypeHANGNEIGUNG_30 = 20,
    STSDKSwisstopoLayerTypeHANGNEIGUNGSKLASSEN_30 = 21,
    STSDKSwisstopoLayerTypeWILDSCHUTZ_GEBIETE = 22,
    STSDKSwisstopoLayerTypeWILDRUHEZONEN = 23,
    STSDKSwisstopoLayerTypeSCHNEESCHUH_ROUTEN = 24,
    STSDKSwisstopoLayerTypeSKI_TOUR_ROUTEN = 25,
    STSDKSwisstopoLayerTypeDROHNEN = 26,
    STSDKSwisstopoLayerTypeSCHUTZGEBIETE_LUFTFAHRT = 27,
};
