// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_configs.djinni
#ifdef __cplusplus

#include "SwisstopoTiledLayerConfigFactory.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class STSDKSwisstopoTiledLayerConfigFactory;

namespace djinni_generated {

class SwisstopoTiledLayerConfigFactory
{
public:
    using CppType = std::shared_ptr<::SwisstopoTiledLayerConfigFactory>;
    using CppOptType = std::shared_ptr<::SwisstopoTiledLayerConfigFactory>;
    using ObjcType = STSDKSwisstopoTiledLayerConfigFactory*;

    using Boxed = SwisstopoTiledLayerConfigFactory;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

#endif
