// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layers.djinni

#import "MCLoaderInterface.h"
#import "MCTiled2dMapRasterLayerInterface.h"
#import "MCTiled2dMapZoomInfo.h"
#import "MCWmtsLayerDescription.h"
#import "STSDKSwisstopoLayerType.h"
#import <Foundation/Foundation.h>


@interface STSDKSwisstopoLayerFactory : NSObject

+ (nullable MCTiled2dMapRasterLayerInterface *)createSwisstopoTiledRasterLayer:(STSDKSwisstopoLayerType)layerType
                                                                        loader:(nullable id<MCLoaderInterface>)loader;

+ (nullable MCTiled2dMapRasterLayerInterface *)createSwisstopoTiledRasterLayerFromMetadata:(nonnull MCWmtsLayerDescription *)description
                                                                                   maxZoom:(int32_t)maxZoom
                                                                                  zoomInfo:(nonnull MCTiled2dMapZoomInfo *)zoomInfo
                                                                                    loader:(nullable id<MCLoaderInterface>)loader;

@end
