// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from open_swiss_maps.djinni
#ifdef __cplusplus

#include "OpenSwissMapsSharedModule.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class STSDKOpenSwissMapsSharedModule;

namespace djinni_generated {

class OpenSwissMapsSharedModule
{
public:
    using CppType = std::shared_ptr<::OpenSwissMapsSharedModule>;
    using CppOptType = std::shared_ptr<::OpenSwissMapsSharedModule>;
    using ObjcType = STSDKOpenSwissMapsSharedModule*;

    using Boxed = OpenSwissMapsSharedModule;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

#endif
