// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_configs.djinni

#import "STSDKSwisstopoTiledLayerConfigFactory+Private.h"
#import "STSDKSwisstopoTiledLayerConfigFactory.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "MCTiled2dMapLayerConfig+Private.h"
#import "MCTiled2dMapZoomInfo+Private.h"
#import "MCWmtsLayerConfiguration+Private.h"
#import "STSDKSwisstopoLayerType+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface STSDKSwisstopoTiledLayerConfigFactory ()

- (id)initWithCpp:(const std::shared_ptr<::SwisstopoTiledLayerConfigFactory>&)cppRef;

@end

@implementation STSDKSwisstopoTiledLayerConfigFactory {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::SwisstopoTiledLayerConfigFactory>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::SwisstopoTiledLayerConfigFactory>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable id<MCTiled2dMapLayerConfig>)createRasterTileLayerConfig:(STSDKSwisstopoLayerType)layerType {
    try {
        auto objcpp_result_ = ::SwisstopoTiledLayerConfigFactory::createRasterTileLayerConfig(::djinni::Enum<::SwisstopoLayerType, STSDKSwisstopoLayerType>::toCpp(layerType));
        return ::djinni_generated::Tiled2dMapLayerConfig::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable id<MCTiled2dMapLayerConfig>)createRasterTiledLayerConfigFromMetadata:(nonnull MCWmtsLayerConfiguration *)configuration
                                                                         maxZoom:(int32_t)maxZoom
                                                                        zoomInfo:(nonnull MCTiled2dMapZoomInfo *)zoomInfo {
    try {
        auto objcpp_result_ = ::SwisstopoTiledLayerConfigFactory::createRasterTiledLayerConfigFromMetadata(::djinni_generated::WmtsLayerConfiguration::toCpp(configuration),
                                                                                                           ::djinni::I32::toCpp(maxZoom),
                                                                                                           ::djinni_generated::Tiled2dMapZoomInfo::toCpp(zoomInfo));
        return ::djinni_generated::Tiled2dMapLayerConfig::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto SwisstopoTiledLayerConfigFactory::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto SwisstopoTiledLayerConfigFactory::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<STSDKSwisstopoTiledLayerConfigFactory>(cpp);
}

}  // namespace djinni_generated

@end
