// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_configs.djinni

#import "MCTiled2dMapLayerConfig.h"
#import "STSDKSwisstopoLayerType.h"
#import <Foundation/Foundation.h>


@interface STSDKSwisstopoTiledLayerConfigFactory : NSObject

+ (nullable id<MCTiled2dMapLayerConfig>)createRasterTileLayerConfig:(STSDKSwisstopoLayerType)layerType;

@end
