// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_configs.djinni
#ifdef __cplusplus
#ifndef __OBJC__

#include "SwisstopoLayerType.h"
#import "DJIMarshal+Private.h"

#endif
#endif
