// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_configs.djinni

#import "MCTiled2dMapLayerConfig.h"
#import "MCTiled2dMapZoomInfo.h"
#import "MCWmtsLayerConfiguration.h"
#import "STSDKSwisstopoLayerType.h"
#import <Foundation/Foundation.h>


@interface STSDKSwisstopoTiledLayerConfigFactory : NSObject

+ (nullable id<MCTiled2dMapLayerConfig>)createRasterTileLayerConfig:(STSDKSwisstopoLayerType)layerType;

+ (nullable id<MCTiled2dMapLayerConfig>)createRasterTiledLayerConfigFromMetadata:(nonnull MCWmtsLayerConfiguration *)configuration
                                                                         maxZoom:(int32_t)maxZoom
                                                                        zoomInfo:(nonnull MCTiled2dMapZoomInfo *)zoomInfo;

@end
