// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_configs.djinni

#import "MCTiled2dMapLayerConfig.h"
#import "MCTiled2dMapZoomInfo.h"
#import "MCTiled2dMapZoomLevelInfo.h"
#import "MCWmtsLayerDescription.h"
#import "STSDKSwisstopoLayerType.h"
#import <Foundation/Foundation.h>


@interface STSDKSwisstopoTiledLayerConfigFactory : NSObject

+ (nullable id<MCTiled2dMapLayerConfig>)createRasterTileLayerConfig:(STSDKSwisstopoLayerType)layerType;

+ (nullable id<MCTiled2dMapLayerConfig>)createRasterTileLayerConfigWithZoomInfo:(STSDKSwisstopoLayerType)layerType
                                                                       zoomInfo:(nullable MCTiled2dMapZoomInfo *)zoomInfo;

+ (nullable id<MCTiled2dMapLayerConfig>)createRasterTileLayerConfigWithBaseUrl:(STSDKSwisstopoLayerType)layerType
                                                                      zoomInfo:(nullable MCTiled2dMapZoomInfo *)zoomInfo
                                                                       baseUrl:(nullable NSString *)baseUrl;

+ (nullable id<MCTiled2dMapLayerConfig>)createRasterTiledLayerConfigFromMetadata:(nonnull MCWmtsLayerDescription *)configuration
                                                                         maxZoom:(int32_t)maxZoom
                                                                        zoomInfo:(nonnull MCTiled2dMapZoomInfo *)zoomInfo;

+ (nonnull NSArray<MCTiled2dMapZoomLevelInfo *> *)createZoomLevelInfos;

@end
