// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layers.djinni
#ifdef __cplusplus

#include "SwisstopoLayerFactory.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class STSDKSwisstopoLayerFactory;

namespace djinni_generated {

class SwisstopoLayerFactory
{
public:
    using CppType = std::shared_ptr<::SwisstopoLayerFactory>;
    using CppOptType = std::shared_ptr<::SwisstopoLayerFactory>;
    using ObjcType = STSDKSwisstopoLayerFactory*;

    using Boxed = SwisstopoLayerFactory;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

#endif
