// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from open_swiss_maps.djinni

package io.openmobilemaps.openswissmaps.kmp

import ch.admin.geo.openswissmaps.shared.OpenSwissMapsSharedModule

actual class KMOpenSwissMapsSharedModule actual public constructor(
    nativeHandle: Any,
) {
    internal val nativeHandle: Any = nativeHandle
    private val native = nativeHandle as OpenSwissMapsSharedModule

    actual companion object
    {

        actual fun version(): String {
            val result = OpenSwissMapsSharedModule.version()
            return result
        }
    }
}

public fun KMOpenSwissMapsSharedModule.asPlatform(): OpenSwissMapsSharedModule = nativeHandle as OpenSwissMapsSharedModule
public fun OpenSwissMapsSharedModule.asKmp(): KMOpenSwissMapsSharedModule = KMOpenSwissMapsSharedModule(this)
