// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layers.djinni

package io.openmobilemaps.openswissmaps.kmp

import io.openmobilemaps.mapscore.kmp.asKmp
import io.openmobilemaps.mapscore.kmp.asPlatform

import ch.admin.geo.openswissmaps.shared.layers.SwisstopoLayerFactory

actual class KMSwisstopoLayerFactory actual public constructor(
    nativeHandle: Any,
) {
    internal val nativeHandle: Any = nativeHandle
    private val native = nativeHandle as SwisstopoLayerFactory

    actual companion object
    {

        actual fun createSwisstopoTiledRasterLayer(layerType: io.openmobilemaps.openswissmaps.kmp.KMSwisstopoLayerType, tileLoaders: List<io.openmobilemaps.mapscore.kmp.KMLoaderInterface>): io.openmobilemaps.mapscore.kmp.KMTiled2dMapRasterLayerInterface {
            val result = SwisstopoLayerFactory.createSwisstopoTiledRasterLayer(layerType.asPlatform(), ArrayList(tileLoaders.map { it.asPlatform() }))
            return (result as io.openmobilemaps.mapscore.shared.map.layers.tiled.raster.Tiled2dMapRasterLayerInterface).asKmp()
        }

        actual fun createSwisstopoTiledRasterLayerFromMetadata(description: io.openmobilemaps.mapscore.kmp.KMWmtsLayerDescription, maxZoom: Int, zoomInfo: io.openmobilemaps.mapscore.kmp.KMTiled2dMapZoomInfo, tileLoaders: List<io.openmobilemaps.mapscore.kmp.KMLoaderInterface>): io.openmobilemaps.mapscore.kmp.KMTiled2dMapRasterLayerInterface {
            val result = SwisstopoLayerFactory.createSwisstopoTiledRasterLayerFromMetadata(description.asPlatform(), maxZoom, zoomInfo.asPlatform(), ArrayList(tileLoaders.map { it.asPlatform() }))
            return (result as io.openmobilemaps.mapscore.shared.map.layers.tiled.raster.Tiled2dMapRasterLayerInterface).asKmp()
        }
    }
}

public fun KMSwisstopoLayerFactory.asPlatform(): SwisstopoLayerFactory = nativeHandle as SwisstopoLayerFactory
public fun SwisstopoLayerFactory.asKmp(): KMSwisstopoLayerFactory = KMSwisstopoLayerFactory(this)
