// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_configs.djinni

package io.openmobilemaps.openswissmaps.kmp

actual typealias KMSwisstopoLayerType = ch.admin.geo.openswissmaps.shared.layers.config.SwisstopoLayerType

public fun KMSwisstopoLayerType.asPlatform(): ch.admin.geo.openswissmaps.shared.layers.config.SwisstopoLayerType = this
public fun ch.admin.geo.openswissmaps.shared.layers.config.SwisstopoLayerType.asKmp(): KMSwisstopoLayerType = this
