// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from layer_configs.djinni

package io.openmobilemaps.openswissmaps.kmp

import io.openmobilemaps.mapscore.kmp.asKmp
import io.openmobilemaps.mapscore.kmp.asPlatform

import ch.admin.geo.openswissmaps.shared.layers.config.SwisstopoTiledLayerConfigFactory

actual class KMSwisstopoTiledLayerConfigFactory actual public constructor(
    nativeHandle: Any,
) {
    internal val nativeHandle: Any = nativeHandle
    private val native = nativeHandle as SwisstopoTiledLayerConfigFactory

    actual companion object
    {

        actual fun createRasterTileLayerConfig(layerType: KMSwisstopoLayerType): io.openmobilemaps.mapscore.kmp.KMTiled2dMapLayerConfig {
            val result = SwisstopoTiledLayerConfigFactory.createRasterTileLayerConfig(layerType.asPlatform())
            return (result as io.openmobilemaps.mapscore.shared.map.layers.tiled.Tiled2dMapLayerConfig).asKmp()
        }

        actual fun createRasterTileLayerConfigWithZoomInfo(layerType: KMSwisstopoLayerType, zoomInfo: io.openmobilemaps.mapscore.kmp.KMTiled2dMapZoomInfo?): io.openmobilemaps.mapscore.kmp.KMTiled2dMapLayerConfig {
            val result = SwisstopoTiledLayerConfigFactory.createRasterTileLayerConfigWithZoomInfo(layerType.asPlatform(), zoomInfo?.let { it.asPlatform() })
            return (result as io.openmobilemaps.mapscore.shared.map.layers.tiled.Tiled2dMapLayerConfig).asKmp()
        }

        actual fun createRasterTileLayerConfigWithBaseUrl(layerType: KMSwisstopoLayerType, zoomInfo: io.openmobilemaps.mapscore.kmp.KMTiled2dMapZoomInfo?, baseUrl: String?): io.openmobilemaps.mapscore.kmp.KMTiled2dMapLayerConfig {
            val result = SwisstopoTiledLayerConfigFactory.createRasterTileLayerConfigWithBaseUrl(layerType.asPlatform(), zoomInfo?.let { it.asPlatform() }, baseUrl?.let { it })
            return (result as io.openmobilemaps.mapscore.shared.map.layers.tiled.Tiled2dMapLayerConfig).asKmp()
        }

        actual fun createRasterTiledLayerConfigFromMetadata(configuration: io.openmobilemaps.mapscore.kmp.KMWmtsLayerDescription, maxZoom: Int, zoomInfo: io.openmobilemaps.mapscore.kmp.KMTiled2dMapZoomInfo): io.openmobilemaps.mapscore.kmp.KMTiled2dMapLayerConfig {
            val result = SwisstopoTiledLayerConfigFactory.createRasterTiledLayerConfigFromMetadata(configuration.asPlatform(), maxZoom, zoomInfo.asPlatform())
            return (result as io.openmobilemaps.mapscore.shared.map.layers.tiled.Tiled2dMapLayerConfig).asKmp()
        }

        actual fun createZoomLevelInfos(): List<io.openmobilemaps.mapscore.kmp.KMTiled2dMapZoomLevelInfo> {
            val result = SwisstopoTiledLayerConfigFactory.createZoomLevelInfos()
            return ArrayList(result.map { (it as io.openmobilemaps.mapscore.shared.map.layers.tiled.Tiled2dMapZoomLevelInfo).asKmp() })
        }
    }
}

public fun KMSwisstopoTiledLayerConfigFactory.asPlatform(): SwisstopoTiledLayerConfigFactory = nativeHandle as SwisstopoTiledLayerConfigFactory
public fun SwisstopoTiledLayerConfigFactory.asKmp(): KMSwisstopoTiledLayerConfigFactory = KMSwisstopoTiledLayerConfigFactory(this)
