// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from open_swiss_maps.djinni

#pragma once

#include "OpenSwissMapsSharedModule.h"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeOpenSwissMapsSharedModule final : ::djinni::JniInterface<::OpenSwissMapsSharedModule, NativeOpenSwissMapsSharedModule> {
public:
    using CppType = std::shared_ptr<::OpenSwissMapsSharedModule>;
    using CppOptType = std::shared_ptr<::OpenSwissMapsSharedModule>;
    using JniType = jobject;

    using Boxed = NativeOpenSwissMapsSharedModule;

    ~NativeOpenSwissMapsSharedModule();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeOpenSwissMapsSharedModule>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeOpenSwissMapsSharedModule>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeOpenSwissMapsSharedModule();
    friend ::djinni::JniClass<NativeOpenSwissMapsSharedModule>;
    friend ::djinni::JniInterface<::OpenSwissMapsSharedModule, NativeOpenSwissMapsSharedModule>;

};

} // namespace djinni_generated
